defaults:
  - _self_
  - prob: kp
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 7
split: train
n_train: 1000
n_test: 100
n_val: 100
sizes:
  - 3-80
  - 4-50
  - 7-40

hydra:
  output_subdir: null
  run:
    dir: .
