defaults:
  - _self_
  - prob: kp
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 7
split: train
from_pid: 0
to_pid: 1
n_processes: 1


hydra:
  output_subdir: null
  run:
    dir: .
