defaults:
  - _self_
  - prob: kp
  - model: gbt
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled


seed: 7
n_train: 1000
n_test: 100
n_val: 100
with_parent: false
layer_weight:
neg_to_pos_ratio: 1
seed_dataset: 2317
n_processes: 1
concat: false

#################
# BDD data config
split: train
from_pid: 0
to_pid: 1000
#################

hydra:
  output_subdir: null
  run:
    dir: .
