defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - prob: kp

seed: 7
split: train
n_train: 1000
n_test: 100
n_val: 100
# tf: transformer
# nn: neural network
# xgb: xgboost
for_model: tf
with_parent: false
layer_weight:
neg_to_pos_ratio: 1
seed_dataset: 2317

hydra:
  output_subdir: null
  run:
    dir: .
