defaults:
  - _self_
  - prob: tsp
  - model: gtf
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

split: test
from_pid: 1100
to_pid: 1200

max_width: 40

hydra:
  output_subdir: null
  run:
    dir: .

