defaults:
  - _self_
  - prob: tsp
  - model: gtf
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# optimizer
optimizer:
  type: Adam
  lr: 1e-3
  decay_lr: false
  min_lr:
  warmup: 0
  wd: 0
  beta1: 0.9
  beta2: 0.999

batch_size: 512
epochs: 10
grad_clip: 0.0
eval_every: 150
weighted_loss: false

# Number of instances to use to create the dataset
# Train max: 1000
# Val/Test max: 100
n_insts:
  train: 100
  val: 100
# Number of negative samples per positive sample
neg_to_pos_ratio: 1
# Fraction of positive samples to use to create the dataset
subsample:
  train: 1
  val: 1
# Resample train dataset for each epoch. Useful when
resample: false


hydra:
  output_subdir: null
  run:
    dir: .

