defaults:
  - _self_
  - prob: tsp
  - model: gtf
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# optimizer
optimizer:
  type: Adam
  lr: 1e-3
  decay_lr: false
  min_lr:
  warmup: 0
  wd: 0
  beta1: 0.9
  beta2: 0.999

batch_size: 512
epochs: 10
grad_clip: 0.0
eval_every: 150
weighted_loss: false

# Resample negative class for each epoch
resample: false
# 0: Do not subsample
# k: Samples k negative data points for one positive data point
subsample:
  train: 1
  val: 1

hydra:
  output_subdir: null
  run:
    dir: .

