defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

prob:
  name: indepset
  prefix: ind
  n_objs: 3
  n_vars: 100
  attach: 4
  seed: 7

size:

# Training config
epochs: 50
refresh_training_dataset: 10
n_inst_per_group: 50
batch_size: 512
n_emb: 128
opt:
  name: Adam
  lr: 1e-3
agg: sum            # cat | sum
dropout: 0
val_every: 5

dataset:
  pid:
    train:
      start: 0
      end: 100
    val:
      start: 1000
      end: 1100

  # Save parents of nodes in the dataset
  with_parent: false
  # Number of negative samples per one positive sample
  neg_to_pos_ratio: 2
  layer_weight: exponential

# Graph_enc
graph_enc:
  n_layers: 2
  n_feat: 4
  n_emb: ${n_emb}
  activation: relu
  dropout: 0.1
  bias: true

# Problem
problem_type: 2
# Is problem is maximization form
maximization: true
# Graph type for Set Packing/Independent Set problem
graph_type: stidsen

hydra:
  output_subdir: null
  run:
    dir: .
