defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

prob:
  name: indepset
  prefix: ind
  n_objs: 3
  n_vars: 100
  attach: 4
  seed: 7

size:

train:
  from_pid: 0
  to_pid: 1
  epochs: 1

val:
  from_pid: 1000
  to_pid: 1001
  every: 1

batch_size: 128
n_emb: 128
opt:
  name: Adam
# cat | add
agg: sum

# Graph_enc
graph_enc:
  n_layers: 2
  n_feat: 4
  n_emb: ${n_emb}
  activation: relu
  dropout: 0.1
  bias: true


# Dataset
problem_type: 2
# Is problem is maximization form
maximization: true
# Graph type for Set Packing/Independent Set problem
graph_type: stidsen
# Save parents of nodes in the dataset
with_parent: false
# Number of negative samples per one positive sample
neg_to_pos_ratio: 10
layer_weight: exponential

hydra:
  output_subdir: null
  run:
    dir: .
