defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

prob:
  name: indepset
  prefix: ind
  n_objs: 3
  n_vars: 100
  attach: 4
  seed: 7

size:

# Training config
logging: 2
epochs: 500
refresh_training_dataset: 5
validate_every: 5
shards_per_epoch: 5
batch_size: 64
# Set this to a positive number when using GPU
n_worker_dataloader: 4

opt:
  name: Adam
  lr: 1e-3
agg: sum            # cat | sum
dropout: 0
val_every: 5

dataset:
  shard:
    train:
      start: 0
      end: 49
    val:
      start: 0
      end: 9

  # Save parents of nodes in the dataset
  with_parent: false
  # Number of negative samples per one positive sample
  neg_to_pos_ratio: 2
  layer_weight: exponential

# Graph_enc
d_emb: 64
top_k: 5
n_blocks: 2
n_heads: 8
bias_mha: false
dropout_mha: 0
bias_mlp: 0.1
dropout_mlp: 0.1
h2i_ratio: 2

# Problem
problem_type: 2
# Is problem is maximization form
maximization: true
# Graph type for Set Packing/Independent Set problem
graph_type: stidsen

hydra:
  output_subdir: null
  run:
    dir: .
