# Gradient-Boosted Tree config
type: gbt
version: 1
max_depth: 5
min_child_weight: 1
subsample: 1
eta: 0.3
colsample_bytree: 1
objective: binary:logistic
num_round: 250
early_stopping_rounds: 20
evals:
  - train
  - val
eval_metric:
  - mae
  - error
  - auc
  - logloss
nthread: 16
seed: 789541
