# Graph transformer config
type: gtf
version: 1
n_node_feat: 2
n_edge_type: 2
d_emb: 32
top_k: 5
n_layers: 4
n_heads: 8
dropout_token: 0
dropout: 0.0
dropout_attn: 0.0
dropout_proj: 0.0
dropout_mlp: 0.0
bias_mha: false
bias_mlp: false
h2i_ratio: 2