max_width: 20
# Problem:
#    - options
#  kp:
#    - random
#    - min_weight
#    - max_weight
#  ind:
#    - random
#    - max_items
#    - min_items
#    - max_value_remaining
node_selection: random


