type: wrbdd
max_width: 20
# Problem:
#    - options
#  kp:
#    - random
#    - min_weight
#    - max_weight (default)
#  ind:
#    - random
#    - max_items (default)
#    - min_items
node_selection: ${prob.node_selection}


