KNAPSACK = "kp"
TSP = "tsp"
MIS = "ind"

GRAPH_TRANSFORMER = "gtf"
GRADIENT_BOOSTED_TREE = "gbt"

HEURISTIC_STATE_SCORER = "heuristic"
SCALER_STATE_SCORER = "scaler"
SET_STATE_SCORER = "set"

TIME_COMPILE = 1
TIME_PARETO = 2
ONE_ARC = 1
ZERO_ARC = -1
RESTRICT = 1
RELAX = 2
